#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

##!
# Get executable path or show an error.
#
# $1 the required executable
# $output the executable full path
##
function require_program {
    local program=$1
    local path

    path=$(command -v "${program}" 2>&1)

    if [[ -z "${path}" ]]; then
        echo "[ERROR] required program not found: ${program}" >&2
        exit 1
    fi

    echo "${path}"
}

##!
# Load configuration file if available.
#
# $1 the configuration file path
##
function maybe_load_config {
    local file_path=$1

    if [[ -f "${file_path}" ]]; then
        source "${file_path}"
    fi
}

CURL=$(require_program curl)
JQ=$(require_program jq)

WALLHAVEN_URL=https://wallhaven.cc
MIN_RESOLUTION=3840x2160
CATEGORIES=100
PURITY=101
SEARCH="nature -tv -anime -video-games -comics -cream -abstract -artwork -car"
WALLPAPERS_DIR=/var/lib/wallpapers
KEEP_DAYS=365

maybe_load_config /etc/wwd.conf
maybe_load_config "${HOME}/.config/wwd/config"

while read -r image_url; do
    ${CURL} -sSLf "${image_url}" --create-dirs --output-dir "${WALLPAPERS_DIR}" -O
done < <(
    ${CURL} -sSLf "${WALLHAVEN_URL}/api/v1/search" -G \
        --data-urlencode "atleast=${MIN_RESOLUTION}" \
        --data-urlencode "categories=${CATEGORIES}" \
        --data-urlencode "purity=${PURITY}" \
        --data-urlencode "q=${SEARCH}" \
        --data-urlencode 'sorting=random' \
        --data-urlencode 'page=1' \
        --data-urlencode "seed=${RANDOM}" \
        | ${JQ} -r ".data[] | .path"
)

if [[ ${KEEP_DAYS} -gt 0 ]]; then
    find "${WALLPAPERS_DIR}" -type f -name 'wallhaven-*' -mtime +${KEEP_DAYS} -delete
fi
